### PR TITLE
Milestone 2 :User interface-demo

### PR DESCRIPTION
**Pull request by vidhishweta01**
It is a demo of the tic tac toe game it represents how the game proceeds what is win move and when the game draw
It is milestone 2 of the project which requires only demo of it its not necessary that it is working as the original game, for the original game please visit branch game_logic or development as that is milestone 3 and it is reviewed and approved
before reviewing please check the requirements of this milestone as per the screenshot given
Screenshot from 2021-02-21 08-02-45

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Required changes:full_moon:
Hi Shweta!
Nice job so far. The codebase is clean and the codes are well thought out and written. However, we still need to make a few changes to get the project approved.

**Mandatory requirements**

- [ ] the game informs the player if the selected move is invalid (without computing what an invalid move is) . When I entered 3 a couple of times. The game still continues without displaying the subsequent move as invalid. Kindly fix it.

- [ ] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))

- [ ] Inside the loop, student should call actions repeated for each move.

 [ ] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable: e.g 
game_on = true

  initial instructions for player

  while game_on
     loop for each move

    if winner # and/or draw (the exact condition in this milestone is not important)
      game_on = false
    end
end

Make the above-required changes and when you are done, request another review.
Kindly drop your questions here and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan.

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Changes Required :yellow_circle: 
### Hello  @vidhishweta01 and @Arinpe :wave: 

#### Thanks for working on the changes suggested and your project passes most of the requirements, but you still can improve your project.

- [ ]  A loop is needed in this game, Please introduce a loop to your game where the loop terminates when certain conditions(win or lose) are met

#### Please work on all changes suggested and submit a new request for review

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by vidhishweta01** [comment]
Screenshot from 2021-02-21 08-02-45

**Comment by vidhishweta01** [comment]
It is milestone 2 of the project which requires only demo of it its not necessary that it is working as the original game for the original game please visit branch game_logic or development as that is milestone 3 and it is reviewed and approved

**Review by Georjane — APPROVED** [review]
## Status: PR Approved 💯 🥇 
### Hi there Team ✋🏽 
Congratulations on successfully completing this milestone. You can go ahead and merge this PR.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on the next milestones and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Pull request merged**
