### PR TITLE
game Instructions

### PR DESCRIPTION
**Pull request by vidhishweta01**

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are some changes required, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] It has a descriptive branch name 💯

- ### To Improve
  - [ ] [MANDATORY] In your `READMe.md` provide the instructions to be followed to run this game localy.
Capture5

  


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on @slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
@slack: Rukundo Eric**

**Review by bini-i — APPROVED** [review]
# Status: Approved :heavy_check_mark:
### Hello  @vidhishweta01 and @Arinpe :wave: 
### Very nice project. Thank you for working on the suggested changes and the project is approved :tada:

## Suggestions
- Please always provide a description of the pull request as it helps explain the changes introduced in the pull request.
- Try to use mark down formatting since it makes your README more readable and engaging.

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Comment by slack** [comment]
@rukundoeric Would you mind updating your signature to not include `@slack`? Every time you comment on a pull request I'm subscribed to the thread and get a ton of email. Thanks!

**Comment by rukundoeric** [comment]
> @rukundoeric Would you mind updating your signature to not include `@slack`? Every time you comment on a pull request I'm subscribed to the thread and get a ton of email. Thanks!

Okay, I will fix that, thanks for reaching out

**Pull request merged**
